-- ============================================================
-- RECUPERACIÓN DE EMERGENCIA — PASO 1 de 2
-- ============================================================
-- Reconstruye desde cero las cuentas del circuito que se borraron. Usa el
-- CSV de credenciales que ya tenías (usuario) + los puntos originales del
-- Excel. Este PASO 1 solo prepara los datos en una tabla de trabajo, no
-- toca todavía jugadores ni auth.users.
--
-- 17 de las 623 filas son categorías que no estaban en el Excel original
-- (se habían cargado después) — quedan con 0 puntos y marcadas
-- "necesita_revision = true" para que las corrijas vos a mano una vez que la
-- gente ya pueda entrar.
-- ============================================================

create extension if not exists pgcrypto;
create extension if not exists unaccent;

drop table if exists _recuperacion_circuito;
create table _recuperacion_circuito (
  nombre_completo text,
  categoria text,
  usuario text,
  puntos numeric(10,1),
  necesita_revision boolean,
  jugador_id uuid,
  clave_persona text
);

insert into _recuperacion_circuito (nombre_completo, categoria, usuario, puntos, necesita_revision) values
  ('Anahel Schreiner', '8va Damas', 'anahel.schreiner@circuito.nortepadel', 2500.0, false),
  ('Anahel Schreiner', '7ma Damas', 'anahel.schreiner2@circuito.nortepadel', 375.0, false),
  ('Angela Hoing', '8va Damas', 'angela.hoing@circuito.nortepadel', 0, true),
  ('Soledad Rojas', '8va Damas', 'soledad.rojas@circuito.nortepadel', 2125.0, false),
  ('Soledad Rojas', '7ma Damas', 'soledad.rojas2@circuito.nortepadel', 125.0, false),
  ('Coni Jara', '7ma Damas', 'coni.jara@circuito.nortepadel', 1250.0, false),
  ('Valentina Rodriguez', '7ma Damas', 'valentina.rodriguez@circuito.nortepadel', 1875.0, false),
  ('Pato Sosa', '8va Damas', 'pato.sosa@circuito.nortepadel', 1750.0, false),
  ('Camila Espinola', '8va Damas', 'camila.espinola@circuito.nortepadel', 0, true),
  ('Camila Espinola', '7ma Damas', 'camila.espinola2@circuito.nortepadel', 750.0, false),
  ('Jazmin Paredes', '8va Damas', 'jazmin.paredes@circuito.nortepadel', 1625.0, false),
  ('Laura Valenzuela', '7ma Damas', 'laura.valenzuela@circuito.nortepadel', 1750.0, false),
  ('Juliana Toloza', '7ma Damas', 'juliana.toloza@circuito.nortepadel', 1000.0, false),
  ('Camila Saucedo', '8va Damas', 'camila.saucedo@circuito.nortepadel', 1500.0, false),
  ('Camila Saucedo', '7ma Damas', 'camila.saucedo2@circuito.nortepadel', 125.0, false),
  ('Camila Schu', '7ma Damas', 'camila.schu@circuito.nortepadel', 1000.0, false),
  ('Glenda Abdalla', '8va Damas', 'glenda.abdalla@circuito.nortepadel', 1375.0, false),
  ('Debora Rodriguez', '8va Damas', 'debora.rodriguez@circuito.nortepadel', 1250.0, false),
  ('Keila Carlino', '8va Damas', 'keila.carlino@circuito.nortepadel', 1125.0, false),
  ('Keila Carlino', '7ma Damas', 'keila.carlino2@circuito.nortepadel', 375.0, false),
  ('Daina Paiva', '8va Damas', 'daina.paiva@circuito.nortepadel', 1125.0, false),
  ('Diana Azame', '7ma Damas', 'diana.azame@circuito.nortepadel', 750.0, false),
  ('Damaris Riveros', '7ma Damas', 'damaris.riveros@circuito.nortepadel', 1000.0, false),
  ('Agostina Aquino', '7ma Damas', 'agostina.aquino@circuito.nortepadel', 750.0, false),
  ('Agustina Bogado', '8va Damas', 'agustina.bogado@circuito.nortepadel', 1000.0, false),
  ('Araceli Diaz', '8va Damas', 'araceli.diaz@circuito.nortepadel', 1000.0, false),
  ('Ana Paula Castelli', '8va Damas', 'ana.paula.castelli@circuito.nortepadel', 1000.0, false),
  ('Ana Paula Castelli', '8va Caballeros', 'ana.paula.castelli2@circuito.nortepadel', 125.0, false),
  ('Noelia Martinez', '8va Damas', 'noelia.martinez@circuito.nortepadel', 875.0, false),
  ('Yani Andrade', '8va Damas', 'yani.andrade@circuito.nortepadel', 875.0, false),
  ('Yani Andrade', '7ma Damas', 'yani.andrade2@circuito.nortepadel', 125.0, false),
  ('Carolina Guerrero', '8va Damas', 'carolina.guerrero@circuito.nortepadel', 750.0, false),
  ('Claudia Rotela', '8va Damas', 'claudia.rotela@circuito.nortepadel', 750.0, false),
  ('Fernanda Elizalde', '8va Damas', 'fernanda.elizalde@circuito.nortepadel', 750.0, false),
  ('Sofia Bado', '8va Damas', 'sofia.bado@circuito.nortepadel', 750.0, false),
  ('Florencia Mercado', '8va Damas', 'florencia.mercado@circuito.nortepadel', 750.0, false),
  ('Gimenza Santa Cruz', '8va Damas', 'gimenza.santa.cruz@circuito.nortepadel', 750.0, false),
  ('Ivone Castrovillari', '8va Damas', 'ivone.castrovillari@circuito.nortepadel', 750.0, false),
  ('Micaela Alegre', '8va Damas', 'micaela.alegre@circuito.nortepadel', 625.0, false),
  ('Luz Romero', '8va Damas', 'luz.romero@circuito.nortepadel', 625.0, false),
  ('Pamela Gonzalez', '8va Damas', 'pamela.gonzalez@circuito.nortepadel', 500.0, false),
  ('Sofia Samudio', '8va Damas', 'sofia.samudio@circuito.nortepadel', 500.0, false),
  ('Sofia Samudio', '7ma Damas', 'sofia.samudio2@circuito.nortepadel', 125.0, false),
  ('Luna Larramendi', '8va Damas', 'luna.larramendi@circuito.nortepadel', 500.0, false),
  ('Antonella Aguirre', '8va Damas', 'antonella.aguirre@circuito.nortepadel', 500.0, false),
  ('Victoria Ledesma', '8va Damas', 'victoria.ledesma@circuito.nortepadel', 500.0, false),
  ('Milagros Gatti', '8va Damas', 'milagros.gatti@circuito.nortepadel', 500.0, false),
  ('Adriana Soto', '8va Damas', 'adriana.soto@circuito.nortepadel', 500.0, false),
  ('Micaela Gautschi', '8va Damas', 'micaela.gautschi@circuito.nortepadel', 500.0, false),
  ('Elena Arriaga', '8va Damas', 'elena.arriaga@circuito.nortepadel', 375.0, false),
  ('Saguchi Akemi', '8va Damas', 'saguchi.akemi@circuito.nortepadel', 375.0, false),
  ('Rosario Schmitz', '8va Damas', 'rosario.schmitz@circuito.nortepadel', 375.0, false),
  ('Lara Dornelles', '8va Damas', 'lara.dornelles@circuito.nortepadel', 375.0, false),
  ('Cynthia Maciel', '8va Damas', 'cynthia.maciel@circuito.nortepadel', 250.0, false),
  ('Eliana Peralta', '8va Damas', 'eliana.peralta@circuito.nortepadel', 250.0, false),
  ('Gimena Baron', '8va Damas', 'gimena.baron@circuito.nortepadel', 250.0, false),
  ('Vero Ruiz Diaz', '8va Damas', 'vero.ruiz.diaz@circuito.nortepadel', 250.0, false),
  ('Vanesa Aguilar', '8va Damas', 'vanesa.aguilar@circuito.nortepadel', 250.0, false),
  ('Griselda Monges', '8va Damas', 'griselda.monges@circuito.nortepadel', 250.0, false),
  ('Isabela Monges', '8va Damas', 'isabela.monges@circuito.nortepadel', 250.0, false),
  ('Viviana Arrua', '8va Damas', 'viviana.arrua@circuito.nortepadel', 250.0, false),
  ('Ori Ledesma', '8va Damas', 'ori.ledesma@circuito.nortepadel', 250.0, false),
  ('Lujan Lugo', '8va Damas', 'lujan.lugo@circuito.nortepadel', 250.0, false),
  ('Agustina Medela', '8va Damas', 'agustina.medela@circuito.nortepadel', 250.0, false),
  ('Betiana Ojeda', '8va Damas', 'betiana.ojeda@circuito.nortepadel', 125.0, false),
  ('Gabriela Fraga', '8va Damas', 'gabriela.fraga@circuito.nortepadel', 125.0, false),
  ('Anto', '8va Damas', 'anto@circuito.nortepadel', 125.0, false),
  ('Yanina Machado', '8va Damas', 'yanina.machado@circuito.nortepadel', 125.0, false),
  ('Micaela Fernanez', '8va Damas', 'micaela.fernanez@circuito.nortepadel', 125.0, false),
  ('Antonela Alises', '8va Damas', 'antonela.alises@circuito.nortepadel', 125.0, false),
  ('Florencia Cabral', '8va Damas', 'florencia.cabral@circuito.nortepadel', 125.0, false),
  ('Milagros Krieger', '8va Damas', 'milagros.krieger@circuito.nortepadel', 125.0, false),
  ('Gabi Montero', '8va Damas', 'gabi.montero@circuito.nortepadel', 125.0, false),
  ('Gabi Montero', '8va Caballeros', 'gabi.montero2@circuito.nortepadel', 125.0, false),
  ('Anto Aguirre', '8va Damas', 'anto.aguirre@circuito.nortepadel', 125.0, false),
  ('Camila Coronel', '8va Damas', 'camila.coronel@circuito.nortepadel', 125.0, false),
  ('Yuli Ferreira', '6ta Damas', 'yuli.ferreira@circuito.nortepadel', 2375.0, false),
  ('Mariana Garganta', '6ta Damas', 'mariana.garganta@circuito.nortepadel', 2375.0, false),
  ('Adriana Regalado', '6ta Damas', 'adriana.regalado@circuito.nortepadel', 2125.0, false),
  ('Eve Villalba', '7ma Damas', 'eve.villalba@circuito.nortepadel', 3250.0, false),
  ('Cristina Gonzalez', '7ma Damas', 'cristina.gonzalez@circuito.nortepadel', 2750.0, false),
  ('Luz Gomez', '6ta Damas', 'luz.gomez@circuito.nortepadel', 1750.0, false),
  ('Valeria Galarza', '7ma Damas', 'valeria.galarza@circuito.nortepadel', 0, true),
  ('Valeria Galarza', '6ta Damas', 'valeria.galarza2@circuito.nortepadel', 2000.0, false),
  ('Valeria Galarza', '7ma Caballeros', 'valeria.galarza3@circuito.nortepadel', 300.0, false),
  ('Sofia Lanes', '7ma Damas', 'sofia.lanes@circuito.nortepadel', 1500.0, false),
  ('Gimenza Toloza', '7ma Damas', 'gimenza.toloza@circuito.nortepadel', 1500.0, false),
  ('Angela Honig', '7ma Damas', 'angela.honig@circuito.nortepadel', 1375.0, false),
  ('Elen Rojas', '7ma Damas', 'elen.rojas@circuito.nortepadel', 1375.0, false),
  ('Vale Castillo', '7ma Damas', 'vale.castillo@circuito.nortepadel', 1250.0, false),
  ('Tati Caradona', '7ma Damas', 'tati.caradona@circuito.nortepadel', 750.0, false),
  ('Marysol Perassi', '7ma Damas', 'marysol.perassi@circuito.nortepadel', 750.0, false),
  ('Valeria Kozak', '7ma Damas', 'valeria.kozak@circuito.nortepadel', 750.0, false),
  ('Nazhira Buiatti', '7ma Damas', 'nazhira.buiatti@circuito.nortepadel', 750.0, false),
  ('Ara Gonzalez', '7ma Damas', 'ara.gonzalez@circuito.nortepadel', 625.0, false),
  ('Vanina Pauluk', '7ma Damas', 'vanina.pauluk@circuito.nortepadel', 625.0, false),
  ('Valeria Guerrero', '7ma Damas', 'valeria.guerrero@circuito.nortepadel', 500.0, false),
  ('Josefina Spalter', '7ma Damas', 'josefina.spalter@circuito.nortepadel', 500.0, false),
  ('Laura Gonzalez', '7ma Damas', 'laura.gonzalez@circuito.nortepadel', 500.0, false),
  ('Flor Lopez', '7ma Damas', 'flor.lopez@circuito.nortepadel', 500.0, false),
  ('Sol Segovia', '7ma Damas', 'sol.segovia@circuito.nortepadel', 250.0, false),
  ('Natalia Pereyra', '7ma Damas', 'natalia.pereyra@circuito.nortepadel', 250.0, false),
  ('Maria Prituluk', '7ma Damas', 'maria.prituluk@circuito.nortepadel', 250.0, false),
  ('Antonela Motta', '7ma Damas', 'antonela.motta@circuito.nortepadel', 250.0, false),
  ('Yessica Zimmerman', '7ma Damas', 'yessica.zimmerman@circuito.nortepadel', 250.0, false),
  ('Marilina Agüero', '7ma Damas', 'marilina.aguero@circuito.nortepadel', 250.0, false),
  ('Valentina Vargas', '7ma Damas', 'valentina.vargas@circuito.nortepadel', 250.0, false),
  ('Antonela Espinoza', '7ma Damas', 'antonela.espinoza@circuito.nortepadel', 250.0, false),
  ('Brenda Nuñez', '7ma Damas', 'brenda.nunez@circuito.nortepadel', 250.0, false),
  ('Antonella Riveros', '7ma Damas', 'antonella.riveros@circuito.nortepadel', 250.0, false),
  ('Leonora Duarte', '7ma Damas', 'leonora.duarte@circuito.nortepadel', 250.0, false),
  ('Celeste Luis', '7ma Damas', 'celeste.luis@circuito.nortepadel', 125.0, false),
  ('Arelys Benitez', '6ta Damas', 'arelys.benitez@circuito.nortepadel', 2000.0, false),
  ('Arelys Benitez', '5ta Damas', 'arelys.benitez2@circuito.nortepadel', 875.0, false),
  ('Arelys Benitez', '7ma Caballeros', 'arelys.benitez3@circuito.nortepadel', 500.0, false),
  ('Renata Rojas', '6ta Damas', 'renata.rojas@circuito.nortepadel', 2000.0, false),
  ('Renata Rojas', '5ta Damas', 'renata.rojas2@circuito.nortepadel', 625.0, false),
  ('Vane Montecino', '6ta Damas', 'vane.montecino@circuito.nortepadel', 1500.0, false),
  ('Rocio Fedriga', '6ta Damas', 'rocio.fedriga@circuito.nortepadel', 1000.0, false),
  ('Rocio Fedriga', '5ta Damas', 'rocio.fedriga2@circuito.nortepadel', 250.0, false),
  ('Anto Cabral', '6ta Damas', 'anto.cabral@circuito.nortepadel', 750.0, false),
  ('Anto Cabral', '5ta Damas', 'anto.cabral2@circuito.nortepadel', 125.0, false),
  ('Fer Olivera', '6ta Damas', 'fer.olivera@circuito.nortepadel', 750.0, false),
  ('Fer Olivera', '5ta Damas', 'fer.olivera2@circuito.nortepadel', 375.0, false),
  ('Luana Cura', '6ta Damas', 'luana.cura@circuito.nortepadel', 750.0, false),
  ('Tatiana Caradona', '6ta Damas', 'tatiana.caradona@circuito.nortepadel', 750.0, false),
  ('Claudia Paez', '6ta Damas', 'claudia.paez@circuito.nortepadel', 500.0, false),
  ('Natalia Araujo', '6ta Damas', 'natalia.araujo@circuito.nortepadel', 500.0, false),
  ('Valentina Centurion', '6ta Damas', 'valentina.centurion@circuito.nortepadel', 250.0, false),
  ('Valentina Centurion', '8va Caballeros', 'valentina.centurion2@circuito.nortepadel', 125.0, false),
  ('Marina Sosa', '6ta Damas', 'marina.sosa@circuito.nortepadel', 250.0, false),
  ('Elsa Thumack', '6ta Damas', 'elsa.thumack@circuito.nortepadel', 250.0, false),
  ('Elsa Thumack', '5ta Damas', 'elsa.thumack2@circuito.nortepadel', 250.0, false),
  ('Rocio Molina', '5ta Damas', 'rocio.molina@circuito.nortepadel', 4250.0, false),
  ('Vandresa Kawaleck', '5ta Damas', 'vandresa.kawaleck@circuito.nortepadel', 0, true),
  ('Fer Spallanzani', '5ta Damas', 'fer.spallanzani@circuito.nortepadel', 0, true),
  ('Carla Lerea', '5ta Damas', 'carla.lerea@circuito.nortepadel', 3000.0, false),
  ('Anyi Cuevas', '5ta Damas', 'anyi.cuevas@circuito.nortepadel', 2750.0, false),
  ('Lorena Zapata', '5ta Damas', 'lorena.zapata@circuito.nortepadel', 1875.0, false),
  ('Malena Ocampo', '5ta Damas', 'malena.ocampo@circuito.nortepadel', 1750.0, false),
  ('Evelin Flor', '5ta Damas', 'evelin.flor@circuito.nortepadel', 1750.0, false),
  ('Ester Rios', '4ta Damas', 'ester.rios@circuito.nortepadel', 1500.0, false),
  ('Laura Doldan', '5ta Damas', 'laura.doldan@circuito.nortepadel', 1500.0, false),
  ('Sofia Sanchez', '5ta Damas', 'sofia.sanchez@circuito.nortepadel', 1500.0, false),
  ('Pamela Gomez', '5ta Damas', 'pamela.gomez@circuito.nortepadel', 1500.0, false),
  ('Jime Kelm', '5ta Damas', 'jime.kelm@circuito.nortepadel', 1500.0, false),
  ('Francisca Acuña', '5ta Damas', 'francisca.acuna@circuito.nortepadel', 1375.0, false),
  ('Perla Maidana', '5ta Damas', 'perla.maidana@circuito.nortepadel', 1250.0, false),
  ('Vanesa Borges', '5ta Damas', 'vanesa.borges@circuito.nortepadel', 1250.0, false),
  ('Anyi Kunzeman', '5ta Damas', 'anyi.kunzeman@circuito.nortepadel', 1125.0, false),
  ('Anyi Kunzeman', '4ta Damas', 'anyi.kunzeman2@circuito.nortepadel', 250.0, false),
  ('Roxi Burgos', '5ta Damas', 'roxi.burgos@circuito.nortepadel', 1000.0, false),
  ('Belen Tarnouski', '5ta Damas', 'belen.tarnouski@circuito.nortepadel', 1000.0, false),
  ('Constanza Wagner', '5ta Damas', 'constanza.wagner@circuito.nortepadel', 875.0, false),
  ('Andrea Kalitko', '5ta Damas', 'andrea.kalitko@circuito.nortepadel', 750.0, false),
  ('Maria Bitancourt', '5ta Damas', 'maria.bitancourt@circuito.nortepadel', 750.0, false),
  ('Sofia Gural', '5ta Damas', 'sofia.gural@circuito.nortepadel', 625.0, false),
  ('Romina Cardozo', '5ta Damas', 'romina.cardozo@circuito.nortepadel', 500.0, false),
  ('Laura Soperes', '5ta Damas', 'laura.soperes@circuito.nortepadel', 500.0, false),
  ('Emilia Fedriga', '5ta Damas', 'emilia.fedriga@circuito.nortepadel', 500.0, false),
  ('Natalia Scholles', '5ta Damas', 'natalia.scholles@circuito.nortepadel', 500.0, false),
  ('Belen Miño', '5ta Damas', 'belen.mino@circuito.nortepadel', 500.0, false),
  ('Reni Wogel', '5ta Damas', 'reni.wogel@circuito.nortepadel', 250.0, false),
  ('Yesica Garcete', '5ta Damas', 'yesica.garcete@circuito.nortepadel', 250.0, false),
  ('Marina', '5ta Damas', 'marina@circuito.nortepadel', 250.0, false),
  ('Alejandra Kalitko', '5ta Damas', 'alejandra.kalitko@circuito.nortepadel', 250.0, false),
  ('Euge Obiedo', '5ta Damas', 'euge.obiedo@circuito.nortepadel', 250.0, false),
  ('Ivana Gauto', '5ta Damas', 'ivana.gauto@circuito.nortepadel', 250.0, false),
  ('Priscila Gonzalez', '5ta Damas', 'priscila.gonzalez@circuito.nortepadel', 125.0, false),
  ('Veronica Kawalec', '5ta Damas', 'veronica.kawalec@circuito.nortepadel', 125.0, false),
  ('Tania Garavano', '5ta Damas', 'tania.garavano@circuito.nortepadel', 125.0, false),
  ('Pato Ostenero', '5ta Damas', 'pato.ostenero@circuito.nortepadel', 125.0, false),
  ('Vanina Ferreira', '5ta Damas', 'vanina.ferreira@circuito.nortepadel', 125.0, false),
  ('Fernanda Spallanzani', '4ta Damas', 'fernanda.spallanzani@circuito.nortepadel', 2750.0, false),
  ('Sol Oggero', '4ta Damas', 'sol.oggero@circuito.nortepadel', 2000.0, false),
  ('Sol Oggero', '6ta Caballeros', 'sol.oggero2@circuito.nortepadel', 625.0, false),
  ('Yanina Miranda', '4ta Damas', 'yanina.miranda@circuito.nortepadel', 2000.0, false),
  ('Vandresa Kawalec', '4ta Damas', 'vandresa.kawalec@circuito.nortepadel', 1750.0, false),
  ('Mariel Russo', '4ta Damas', 'mariel.russo@circuito.nortepadel', 1250.0, false),
  ('Nicole Domacinovic', '4ta Damas', 'nicole.domacinovic@circuito.nortepadel', 750.0, false),
  ('Gladys Olmedo', '4ta Damas', 'gladys.olmedo@circuito.nortepadel', 750.0, false),
  ('Luz Samudio', '4ta Damas', 'luz.samudio@circuito.nortepadel', 750.0, false),
  ('Susi Rios', '4ta Damas', 'susi.rios@circuito.nortepadel', 750.0, false),
  ('Beti Borges', '4ta Damas', 'beti.borges@circuito.nortepadel', 500.0, false),
  ('Simone Schweizer', '4ta Damas', 'simone.schweizer@circuito.nortepadel', 500.0, false),
  ('Pilar Cenoz', '4ta Damas', 'pilar.cenoz@circuito.nortepadel', 500.0, false),
  ('Anyi Cueva', '4ta Damas', 'anyi.cueva@circuito.nortepadel', 250.0, false),
  ('Raquel Colman', '4ta Damas', 'raquel.colman@circuito.nortepadel', 250.0, false),
  ('Sil Ramos', '4ta Damas', 'sil.ramos@circuito.nortepadel', 250.0, false),
  ('Mauricio Lemes', '8va Caballeros', 'mauricio.lemes@circuito.nortepadel', 0, true),
  ('Lisandro Gonzalez', '7ma Caballeros', 'lisandro.gonzalez@circuito.nortepadel', 1250.0, false),
  ('Benjamin Morinigo', '7ma Caballeros', 'benjamin.morinigo@circuito.nortepadel', 1250.0, false),
  ('Marcos Ojeda', '7ma Caballeros', 'marcos.ojeda@circuito.nortepadel', 1225.0, false),
  ('Lautaro Zerbatto', '7ma Caballeros', 'lautaro.zerbatto@circuito.nortepadel', 1075.0, false),
  ('Ezequiel Villalba', '8va Caballeros', 'ezequiel.villalba@circuito.nortepadel', 1625.0, false),
  ('Emanuel Bogado', '7ma Caballeros', 'emanuel.bogado@circuito.nortepadel', 750.0, false),
  ('Matias Caceres', '7ma Caballeros', 'matias.caceres@circuito.nortepadel', 750.0, false),
  ('Lautaro Vizgarra', '8va Caballeros', 'lautaro.vizgarra@circuito.nortepadel', 1375.0, false),
  ('Alexis Pereira', '8va Caballeros', 'alexis.pereira@circuito.nortepadel', 1375.0, false),
  ('Alexis Fraga', '8va Caballeros', 'alexis.fraga@circuito.nortepadel', 0, true),
  ('Alexis Fraga', '7ma Caballeros', 'alexis.fraga2@circuito.nortepadel', 1450.0, false),
  ('Alexis Fraga', '6ta Caballeros', 'alexis.fraga3@circuito.nortepadel', 250.0, false),
  ('Richard Britez', '8va Caballeros', 'richard.britez@circuito.nortepadel', 1250.0, false),
  ('Richard Britez', '7ma Caballeros', 'richard.britez2@circuito.nortepadel', 200.0, false),
  ('Lucas Suarez', '8va Caballeros', 'lucas.suarez@circuito.nortepadel', 1250.0, false),
  ('Mauricio Cardozo', '8va Caballeros', 'mauricio.cardozo@circuito.nortepadel', 1250.0, false),
  ('Brian Leguizamon', '8va Caballeros', 'brian.leguizamon@circuito.nortepadel', 1125.0, false),
  ('Brian Leguizamon', '7ma Caballeros', 'brian.leguizamon2@circuito.nortepadel', 100.0, false),
  ('Uriel Zamudio', '7ma Caballeros', 'uriel.zamudio@circuito.nortepadel', 700.0, false),
  ('Chiqui Rodriguez', '8va Caballeros', 'chiqui.rodriguez@circuito.nortepadel', 0, true),
  ('Chiqui Rodriguez', '7ma Caballeros', 'chiqui.rodriguez2@circuito.nortepadel', 0, true),
  ('Chiqui Rodriguez', '6ta Caballeros', 'chiqui.rodriguez3@circuito.nortepadel', 1362.5, false),
  ('Ian Rodriguez', '8va Caballeros', 'ian.rodriguez@circuito.nortepadel', 1000.0, false),
  ('Ian Rodriguez', '7ma Caballeros', 'ian.rodriguez2@circuito.nortepadel', 1000.0, false),
  ('Gabriel Duarte', '7ma Caballeros', 'gabriel.duarte@circuito.nortepadel', 725.0, false),
  ('Francisco Barreto', '7ma Caballeros', 'francisco.barreto@circuito.nortepadel', 500.0, false),
  ('Leandro Castelli', '8va Caballeros', 'leandro.castelli@circuito.nortepadel', 1000.0, false),
  ('Leandro Castelli', '7ma Caballeros', 'leandro.castelli2@circuito.nortepadel', 325.0, false),
  ('Ignacio Indavera', '7ma Caballeros', 'ignacio.indavera@circuito.nortepadel', 500.0, false),
  ('Lucas Larramendia', '8va Caballeros', 'lucas.larramendia@circuito.nortepadel', 875.0, false),
  ('Alan Benitez', '8va Caballeros', 'alan.benitez@circuito.nortepadel', 875.0, false),
  ('Migue Sanabria', '8va Caballeros', 'migue.sanabria@circuito.nortepadel', 875.0, false),
  ('Kevin Meireles', '7ma Caballeros', 'kevin.meireles@circuito.nortepadel', 475.0, false),
  ('Joaquin Caceres', '8va Caballeros', 'joaquin.caceres@circuito.nortepadel', 625.0, false),
  ('Emiliano Alfonoso', '8va Caballeros', 'emiliano.alfonoso@circuito.nortepadel', 625.0, false),
  ('Geremias Krieger', '8va Caballeros', 'geremias.krieger@circuito.nortepadel', 625.0, false),
  ('Fernando Nielsen', '8va Caballeros', 'fernando.nielsen@circuito.nortepadel', 500.0, false),
  ('Renzo Benitez', '8va Caballeros', 'renzo.benitez@circuito.nortepadel', 500.0, false),
  ('Erni Bush', '8va Caballeros', 'erni.bush@circuito.nortepadel', 500.0, false),
  ('Diego Martin', '8va Caballeros', 'diego.martin@circuito.nortepadel', 500.0, false),
  ('Ezequiel Vera', '8va Caballeros', 'ezequiel.vera@circuito.nortepadel', 500.0, false),
  ('Ronald Vier', '8va Caballeros', 'ronald.vier@circuito.nortepadel', 500.0, false),
  ('Facundo Amigot', '8va Caballeros', 'facundo.amigot@circuito.nortepadel', 500.0, false),
  ('Matheo Montero', '8va Caballeros', 'matheo.montero@circuito.nortepadel', 500.0, false),
  ('Jeremias Gimenez', '8va Caballeros', 'jeremias.gimenez@circuito.nortepadel', 375.0, false),
  ('Braian Lopez', '8va Caballeros', 'braian.lopez@circuito.nortepadel', 375.0, false),
  ('Lucas Sanchez', '8va Caballeros', 'lucas.sanchez@circuito.nortepadel', 375.0, false),
  ('Alexis Rojas', '8va Caballeros', 'alexis.rojas@circuito.nortepadel', 375.0, false),
  ('Alexis Rojas', '7ma Caballeros', 'alexis.rojas2@circuito.nortepadel', 125.0, false),
  ('Francisco Corde', '8va Caballeros', 'francisco.corde@circuito.nortepadel', 250.0, false),
  ('Gabriel Braun', '8va Caballeros', 'gabriel.braun@circuito.nortepadel', 250.0, false),
  ('Charly Segovia', '8va Caballeros', 'charly.segovia@circuito.nortepadel', 250.0, false),
  ('Lucas Rodriguez', '8va Caballeros', 'lucas.rodriguez@circuito.nortepadel', 250.0, false),
  ('Sergio Peralta', '8va Caballeros', 'sergio.peralta@circuito.nortepadel', 250.0, false),
  ('Ian Gomez', '8va Caballeros', 'ian.gomez@circuito.nortepadel', 250.0, false),
  ('Nacho Mazal', '8va Caballeros', 'nacho.mazal@circuito.nortepadel', 250.0, false),
  ('Sotelo', '8va Caballeros', 'sotelo@circuito.nortepadel', 250.0, false),
  ('Bautista Rodriguez', '8va Caballeros', 'bautista.rodriguez@circuito.nortepadel', 250.0, false),
  ('Daniel Spaciuk', '8va Caballeros', 'daniel.spaciuk@circuito.nortepadel', 250.0, false),
  ('Yoni Baez', '8va Caballeros', 'yoni.baez@circuito.nortepadel', 250.0, false),
  ('Maxi Candia', '8va Caballeros', 'maxi.candia@circuito.nortepadel', 250.0, false),
  ('Jonas Bado', '8va Caballeros', 'jonas.bado@circuito.nortepadel', 250.0, false),
  ('Benjamin Talalay', '8va Caballeros', 'benjamin.talalay@circuito.nortepadel', 250.0, false),
  ('Teo Torres', '8va Caballeros', 'teo.torres@circuito.nortepadel', 250.0, false),
  ('Valentino Morales', '8va Caballeros', 'valentino.morales@circuito.nortepadel', 250.0, false),
  ('Francisco Ortega', '8va Caballeros', 'francisco.ortega@circuito.nortepadel', 250.0, false),
  ('Emanuel Espinola', '8va Caballeros', 'emanuel.espinola@circuito.nortepadel', 250.0, false),
  ('Ruben Ramirez', '8va Caballeros', 'ruben.ramirez@circuito.nortepadel', 250.0, false),
  ('Enrique Rivas', '8va Caballeros', 'enrique.rivas@circuito.nortepadel', 250.0, false),
  ('Valentin Martinez', '8va Caballeros', 'valentin.martinez@circuito.nortepadel', 125.0, false),
  ('Felipe Contreras', '8va Caballeros', 'felipe.contreras@circuito.nortepadel', 125.0, false),
  ('Agustin Gimenez', '8va Caballeros', 'agustin.gimenez@circuito.nortepadel', 125.0, false),
  ('Waldo Fralliccardi', '8va Caballeros', 'waldo.fralliccardi@circuito.nortepadel', 125.0, false),
  ('Emanuel Villalba', '8va Caballeros', 'emanuel.villalba@circuito.nortepadel', 125.0, false),
  ('Santiago Wesler', '8va Caballeros', 'santiago.wesler@circuito.nortepadel', 125.0, false),
  ('Gonza Gomez', '8va Caballeros', 'gonza.gomez@circuito.nortepadel', 125.0, false),
  ('Lisandro Pereira', '8va Caballeros', 'lisandro.pereira@circuito.nortepadel', 125.0, false),
  ('Marcelo Rojas', '8va Caballeros', 'marcelo.rojas@circuito.nortepadel', 125.0, false),
  ('Mauri Montejano', '8va Caballeros', 'mauri.montejano@circuito.nortepadel', 125.0, false),
  ('Marcos Markievich', '8va Caballeros', 'marcos.markievich@circuito.nortepadel', 125.0, false),
  ('Iñaki Debelaustegui', '8va Caballeros', 'inaki.debelaustegui@circuito.nortepadel', 125.0, false),
  ('Thiago Cuña', '8va Caballeros', 'thiago.cuna@circuito.nortepadel', 125.0, false),
  ('Mariano Ulbina', '8va Caballeros', 'mariano.ulbina@circuito.nortepadel', 125.0, false),
  ('Franco Woronovich', '8va Caballeros', 'franco.woronovich@circuito.nortepadel', 125.0, false),
  ('Mateo Diaz', '7ma Caballeros', 'mateo.diaz@circuito.nortepadel', 3000.0, false),
  ('Mauro Valerio', '7ma Caballeros', 'mauro.valerio@circuito.nortepadel', 2600.0, false),
  ('Mauro Valerio', '6ta Caballeros', 'mauro.valerio2@circuito.nortepadel', 125.0, false),
  ('Benjamin Casales', '6ta Caballeros', 'benjamin.casales@circuito.nortepadel', 1300.0, false),
  ('Ulises Rivas', '6ta Caballeros', 'ulises.rivas@circuito.nortepadel', 1125.0, false),
  ('Ramiro Garcia', '6ta Caballeros', 'ramiro.garcia@circuito.nortepadel', 1125.0, false),
  ('Marcelo Ledesma', '6ta Caballeros', 'marcelo.ledesma@circuito.nortepadel', 1487.5, false),
  ('Mauri Lemes', '7ma Caballeros', 'mauri.lemes@circuito.nortepadel', 1787.5, false),
  ('Rodrigo Baez', '6ta Caballeros', 'rodrigo.baez@circuito.nortepadel', 987.5, false),
  ('Alvaro Cabrera', '7ma Caballeros', 'alvaro.cabrera@circuito.nortepadel', 1625.0, false),
  ('Alvaro Cabrera', '6ta Caballeros', 'alvaro.cabrera2@circuito.nortepadel', 250.0, false),
  ('Lucas Lopez', '6ta Caballeros', 'lucas.lopez@circuito.nortepadel', 750.0, false),
  ('Facu Jardin', '7ma Caballeros', 'facu.jardin@circuito.nortepadel', 1475.0, false),
  ('Facu Jardin', '6ta Caballeros', 'facu.jardin2@circuito.nortepadel', 250.0, false),
  ('Nicolas Portillo', '7ma Caballeros', 'nicolas.portillo@circuito.nortepadel', 1300.0, false),
  ('Nicolas Portillo', '6ta Caballeros', 'nicolas.portillo2@circuito.nortepadel', 375.0, false),
  ('Joaquin Nolasco', '6ta Caballeros', 'joaquin.nolasco@circuito.nortepadel', 2375.0, false),
  ('Luciano Rodriguez', '7ma Caballeros', 'luciano.rodriguez@circuito.nortepadel', 1250.0, false),
  ('Marcos Zipp', '7ma Caballeros', 'marcos.zipp@circuito.nortepadel', 1250.0, false),
  ('Victor Peralta', '7ma Caballeros', 'victor.peralta@circuito.nortepadel', 1125.0, false),
  ('Alejandro Enrique', '7ma Caballeros', 'alejandro.enrique@circuito.nortepadel', 1125.0, false),
  ('Ale Reynoso', '7ma Caballeros', 'ale.reynoso@circuito.nortepadel', 1100.0, false),
  ('Nico De Lima', '6ta Caballeros', 'nico.de.lima@circuito.nortepadel', 1375.0, false),
  ('Ezequiel Avalos', '7ma Caballeros', 'ezequiel.avalos@circuito.nortepadel', 1000.0, false),
  ('Ema Serrudo', '7ma Caballeros', 'ema.serrudo@circuito.nortepadel', 1000.0, false),
  ('Cesar De Souza', '7ma Caballeros', 'cesar.de.souza@circuito.nortepadel', 975.0, false),
  ('Wilson', '7ma Caballeros', 'wilson@circuito.nortepadel', 950.0, false),
  ('Sebastian Valdez', '7ma Caballeros', 'sebastian.valdez@circuito.nortepadel', 875.0, false),
  ('Elias Toledo', '7ma Caballeros', 'elias.toledo@circuito.nortepadel', 850.0, false),
  ('Francisco Portillo', '7ma Caballeros', 'francisco.portillo@circuito.nortepadel', 825.0, false),
  ('Alexander Benitez', '7ma Caballeros', 'alexander.benitez@circuito.nortepadel', 750.0, false),
  ('Maximo Benitez', '7ma Caballeros', 'maximo.benitez@circuito.nortepadel', 750.0, false),
  ('Esteban Saucedo', '7ma Caballeros', 'esteban.saucedo@circuito.nortepadel', 750.0, false),
  ('Jorge Quiroz', '7ma Caballeros', 'jorge.quiroz@circuito.nortepadel', 750.0, false),
  ('Jonatan Paniagua', '7ma Caballeros', 'jonatan.paniagua@circuito.nortepadel', 750.0, false),
  ('Marcelo Sugasti', '6ta Caballeros', 'marcelo.sugasti@circuito.nortepadel', 375.0, false),
  ('Felipe Cagnola', '6ta Caballeros', 'felipe.cagnola@circuito.nortepadel', 1112.5, false),
  ('Nahuel Ruiz', '7ma Caballeros', 'nahuel.ruiz@circuito.nortepadel', 700.0, false),
  ('Nikito Pereira', '7ma Caballeros', 'nikito.pereira@circuito.nortepadel', 675.0, false),
  ('Santino Larramendia', '7ma Caballeros', 'santino.larramendia@circuito.nortepadel', 650.0, false),
  ('Carlos Chagas', '7ma Caballeros', 'carlos.chagas@circuito.nortepadel', 625.0, false),
  ('Carlos Chagas', '6ta Caballeros', 'carlos.chagas2@circuito.nortepadel', 250.0, false),
  ('German Ocampo', '7ma Caballeros', 'german.ocampo@circuito.nortepadel', 550.0, false),
  ('Esteban Alvarenga', '7ma Caballeros', 'esteban.alvarenga@circuito.nortepadel', 500.0, false),
  ('Esteban Alvarenga', '6ta Caballeros', 'esteban.alvarenga2@circuito.nortepadel', 250.0, false),
  ('Daniel Nazaruk', '7ma Caballeros', 'daniel.nazaruk@circuito.nortepadel', 500.0, false),
  ('Eduardo Rodriguez', '7ma Caballeros', 'eduardo.rodriguez@circuito.nortepadel', 500.0, false),
  ('Franco Duarte', '7ma Caballeros', 'franco.duarte@circuito.nortepadel', 500.0, false),
  ('Cristian Fritzler', '6ta Caballeros', 'cristian.fritzler@circuito.nortepadel', 250.0, false),
  ('Cesar Garcia', '7ma Caballeros', 'cesar.garcia@circuito.nortepadel', 450.0, false),
  ('Matias Sausen', '7ma Caballeros', 'matias.sausen@circuito.nortepadel', 450.0, false),
  ('Tata Rojas', '7ma Caballeros', 'tata.rojas@circuito.nortepadel', 450.0, false),
  ('Tata Rojas', '6ta Caballeros', 'tata.rojas2@circuito.nortepadel', 100.0, false),
  ('Jose Acosta', '7ma Caballeros', 'jose.acosta@circuito.nortepadel', 375.0, false),
  ('Jonas Aguirre', '7ma Caballeros', 'jonas.aguirre@circuito.nortepadel', 375.0, false),
  ('Maxi Neris', '7ma Caballeros', 'maxi.neris@circuito.nortepadel', 375.0, false),
  ('Jorge Gaztke', '7ma Caballeros', 'jorge.gaztke@circuito.nortepadel', 375.0, false),
  ('Marcelo Norfors', '7ma Caballeros', 'marcelo.norfors@circuito.nortepadel', 375.0, false),
  ('Yonatan Keller', '7ma Caballeros', 'yonatan.keller@circuito.nortepadel', 375.0, false),
  ('Damian Ramon', '7ma Caballeros', 'damian.ramon@circuito.nortepadel', 375.0, false),
  ('Damian Ramon', '6ta Caballeros', 'damian.ramon2@circuito.nortepadel', 125.0, false),
  ('Guillermo Barrios', '7ma Caballeros', 'guillermo.barrios@circuito.nortepadel', 350.0, false),
  ('Daniel Santucho', '7ma Caballeros', 'daniel.santucho@circuito.nortepadel', 350.0, false),
  ('Eze Gonzalez', '7ma Caballeros', 'eze.gonzalez@circuito.nortepadel', 350.0, false),
  ('Lautaro Avalos', '7ma Caballeros', 'lautaro.avalos@circuito.nortepadel', 350.0, false),
  ('Nicolas Santini', '7ma Caballeros', 'nicolas.santini@circuito.nortepadel', 350.0, false),
  ('Juan Bado', '7ma Caballeros', 'juan.bado@circuito.nortepadel', 350.0, false),
  ('Juanjo Nuñez', '7ma Caballeros', 'juanjo.nunez@circuito.nortepadel', 300.0, false),
  ('Ian De Lima', '7ma Caballeros', 'ian.de.lima@circuito.nortepadel', 250.0, false),
  ('Javier Sortica', '7ma Caballeros', 'javier.sortica@circuito.nortepadel', 250.0, false),
  ('Guillermo Fernandez', '7ma Caballeros', 'guillermo.fernandez@circuito.nortepadel', 250.0, false),
  ('Diego Irala', '7ma Caballeros', 'diego.irala@circuito.nortepadel', 250.0, false),
  ('Miguel Morais', '7ma Caballeros', 'miguel.morais@circuito.nortepadel', 250.0, false),
  ('Chino', '7ma Caballeros', 'chino@circuito.nortepadel', 250.0, false),
  ('Brandon Machado', '7ma Caballeros', 'brandon.machado@circuito.nortepadel', 250.0, false),
  ('Gringo Busch', '7ma Caballeros', 'gringo.busch@circuito.nortepadel', 225.0, false),
  ('Claudio Kluba', '7ma Caballeros', 'claudio.kluba@circuito.nortepadel', 225.0, false),
  ('Alan Capitan', '7ma Caballeros', 'alan.capitan@circuito.nortepadel', 225.0, false),
  ('Alma Rojas', '7ma Caballeros', 'alma.rojas@circuito.nortepadel', 125.0, false),
  ('Rodrigo Gonzalez', '7ma Caballeros', 'rodrigo.gonzalez@circuito.nortepadel', 125.0, false),
  ('Raul Amarilla', '7ma Caballeros', 'raul.amarilla@circuito.nortepadel', 125.0, false),
  ('Tito Fernandez', '7ma Caballeros', 'tito.fernandez@circuito.nortepadel', 125.0, false),
  ('Jonathan Paredes', '7ma Caballeros', 'jonathan.paredes@circuito.nortepadel', 125.0, false),
  ('Diego Gonzalez', '7ma Caballeros', 'diego.gonzalez@circuito.nortepadel', 125.0, false),
  ('Enzo Ferreira', '7ma Caballeros', 'enzo.ferreira@circuito.nortepadel', 125.0, false),
  ('Juan Martin Rojas', '7ma Caballeros', 'juan.martin.rojas@circuito.nortepadel', 125.0, false),
  ('Marcos Balbuena', '7ma Caballeros', 'marcos.balbuena@circuito.nortepadel', 125.0, false),
  ('Valen Masia', '7ma Caballeros', 'valen.masia@circuito.nortepadel', 125.0, false),
  ('Valen Masia', '6ta Caballeros', 'valen.masia2@circuito.nortepadel', 125.0, false),
  ('Sebastian Dearruda', '7ma Caballeros', 'sebastian.dearruda@circuito.nortepadel', 125.0, false),
  ('Sebastian Montero', '7ma Caballeros', 'sebastian.montero@circuito.nortepadel', 125.0, false),
  ('Jairo Silva', '7ma Caballeros', 'jairo.silva@circuito.nortepadel', 100.0, false),
  ('Luis Biondi', '7ma Caballeros', 'luis.biondi@circuito.nortepadel', 100.0, false),
  ('Jonatan Paredes', '7ma Caballeros', 'jonatan.paredes@circuito.nortepadel', 100.0, false),
  ('Enzo Andino', '7ma Caballeros', 'enzo.andino@circuito.nortepadel', 100.0, false),
  ('Mario Cieslik', '7ma Caballeros', 'mario.cieslik@circuito.nortepadel', 100.0, false),
  ('Matias Fernandez', '7ma Caballeros', 'matias.fernandez@circuito.nortepadel', 100.0, false),
  ('Lucas Vera', '7ma Caballeros', 'lucas.vera@circuito.nortepadel', 100.0, false),
  ('Enzo Marquez', '7ma Caballeros', 'enzo.marquez@circuito.nortepadel', 100.0, false),
  ('Santiago Santacruz', '7ma Caballeros', 'santiago.santacruz@circuito.nortepadel', 100.0, false),
  ('Agustin Rojas', '6ta Caballeros', 'agustin.rojas@circuito.nortepadel', 50.0, false),
  ('Adrian Herrera', '7ma Caballeros', 'adrian.herrera@circuito.nortepadel', 100.0, false),
  ('Horacio Caballero', '7ma Caballeros', 'horacio.caballero@circuito.nortepadel', 100.0, false),
  ('Roberto Meza', '7ma Caballeros', 'roberto.meza@circuito.nortepadel', 100.0, false),
  ('Marcelo Cagnola', '7ma Caballeros', 'marcelo.cagnola@circuito.nortepadel', 100.0, false),
  ('Roberto Garcia', '7ma Caballeros', 'roberto.garcia@circuito.nortepadel', 100.0, false),
  ('Claudio Godoy', '7ma Caballeros', 'claudio.godoy@circuito.nortepadel', 100.0, false),
  ('Tuki Portillo', '7ma Caballeros', 'tuki.portillo@circuito.nortepadel', 100.0, false),
  ('Alex Benitez', '7ma Caballeros', 'alex.benitez@circuito.nortepadel', 100.0, false),
  ('Alejandro Pico', '7ma Caballeros', 'alejandro.pico@circuito.nortepadel', 100.0, false),
  ('Tomas Hofsetz', '5ta Caballeros', 'tomas.hofsetz@circuito.nortepadel', 2125.0, false),
  ('Nicolas Martinez', '5ta Caballeros', 'nicolas.martinez@circuito.nortepadel', 2125.0, false),
  ('Cristian Gautschi', '6ta Caballeros', 'cristian.gautschi@circuito.nortepadel', 3000.0, false),
  ('Patricio Esquivel', '6ta Caballeros', 'patricio.esquivel@circuito.nortepadel', 125.0, false),
  ('Patricio Esquivel', '6ta Caballeros', 'patricio.esquivel2@circuito.nortepadel', 125.0, false),
  ('Patricio Esquivel', '5ta Caballeros', 'patricio.esquivel3@circuito.nortepadel', 1125.0, false),
  ('Kevin Schmitz', '6ta Caballeros', 'kevin.schmitz@circuito.nortepadel', 2125.0, false),
  ('Maxi Diaz', '6ta Caballeros', 'maxi.diaz@circuito.nortepadel', 2000.0, false),
  ('Lautaro Pereira', '5ta Caballeros', 'lautaro.pereira@circuito.nortepadel', 1162.5, false),
  ('Ale Lopez', '6ta Caballeros', 'ale.lopez@circuito.nortepadel', 1500.0, false),
  ('Matias Machado', '6ta Caballeros', 'matias.machado@circuito.nortepadel', 1500.0, false),
  ('Gaston Vieira', '6ta Caballeros', 'gaston.vieira@circuito.nortepadel', 1500.0, false),
  ('Gaston Vieira', '5ta Caballeros', 'gaston.vieira2@circuito.nortepadel', 250.0, false),
  ('Facundo Da Silva', '6ta Caballeros', 'facundo.da.silva@circuito.nortepadel', 1250.0, false),
  ('Facundo Da Silva', '5ta Caballeros', 'facundo.da.silva2@circuito.nortepadel', 625.0, false),
  ('Cristian Casales', '6ta Caballeros', 'cristian.casales@circuito.nortepadel', 1125.0, false),
  ('Cristian Gaedicke', '6ta Caballeros', 'cristian.gaedicke@circuito.nortepadel', 1125.0, false),
  ('Cristian Gaedicke', '5ta Caballeros', 'cristian.gaedicke2@circuito.nortepadel', 225.0, false),
  ('Facundo Brunori', '6ta Caballeros', 'facundo.brunori@circuito.nortepadel', 1125.0, false),
  ('Pablo Saucedo', '6ta Caballeros', 'pablo.saucedo@circuito.nortepadel', 1125.0, false),
  ('Rodrigo Villalba', '6ta Caballeros', 'rodrigo.villalba@circuito.nortepadel', 1000.0, false),
  ('Leo Baez', '6ta Caballeros', 'leo.baez@circuito.nortepadel', 1000.0, false),
  ('Alex Da Rosa', '5ta Caballeros', 'alex.da.rosa@circuito.nortepadel', 2162.5, false),
  ('Juanchi De Lima', '6ta Caballeros', 'juanchi.de.lima@circuito.nortepadel', 875.0, false),
  ('Juanchi De Lima', '5ta Caballeros', 'juanchi.de.lima2@circuito.nortepadel', 375.0, false),
  ('Harry Foos', '6ta Caballeros', 'harry.foos@circuito.nortepadel', 875.0, false),
  ('Edu Kozak', '6ta Caballeros', 'edu.kozak@circuito.nortepadel', 875.0, false),
  ('Walter Quintana', '6ta Caballeros', 'walter.quintana@circuito.nortepadel', 750.0, false),
  ('Roque Soto', '6ta Caballeros', 'roque.soto@circuito.nortepadel', 625.0, false),
  ('Fer De Lima', '6ta Caballeros', 'fer.de.lima@circuito.nortepadel', 625.0, false),
  ('Rodrigo Camacho', '6ta Caballeros', 'rodrigo.camacho@circuito.nortepadel', 625.0, false),
  ('Claudio Bogado', '6ta Caballeros', 'claudio.bogado@circuito.nortepadel', 625.0, false),
  ('Cristian Ramirez', '6ta Caballeros', 'cristian.ramirez@circuito.nortepadel', 625.0, false),
  ('Yani Miranda', '6ta Caballeros', 'yani.miranda@circuito.nortepadel', 625.0, false),
  ('Lucas Baudino', '6ta Caballeros', 'lucas.baudino@circuito.nortepadel', 500.0, false),
  ('Santiago Zavala', '6ta Caballeros', 'santiago.zavala@circuito.nortepadel', 500.0, false),
  ('Santiago Zavala', '5ta Caballeros', 'santiago.zavala2@circuito.nortepadel', 250.0, false),
  ('Matias Zavala', '6ta Caballeros', 'matias.zavala@circuito.nortepadel', 500.0, false),
  ('Angelo Silvestri', '6ta Caballeros', 'angelo.silvestri@circuito.nortepadel', 475.0, false),
  ('Javier Verite', '6ta Caballeros', 'javier.verite@circuito.nortepadel', 475.0, false),
  ('Mateo Stolaruk', '6ta Caballeros', 'mateo.stolaruk@circuito.nortepadel', 375.0, false),
  ('Tiago Gautschi', '5ta Caballeros', 'tiago.gautschi@circuito.nortepadel', 2687.5, false),
  ('Cristian Peña', '6ta Caballeros', 'cristian.pena@circuito.nortepadel', 375.0, false),
  ('Mario Arregin', '6ta Caballeros', 'mario.arregin@circuito.nortepadel', 375.0, false),
  ('Javier Rojas', '6ta Caballeros', 'javier.rojas@circuito.nortepadel', 350.0, false),
  ('Javier Rojas', '5ta Caballeros', 'javier.rojas2@circuito.nortepadel', 575.0, false),
  ('Tano Loprette', '6ta Caballeros', 'tano.loprette@circuito.nortepadel', 350.0, false),
  ('Joaquin Dachary', '6ta Caballeros', 'joaquin.dachary@circuito.nortepadel', 250.0, false),
  ('Elias Esquivel', '6ta Caballeros', 'elias.esquivel@circuito.nortepadel', 250.0, false),
  ('Nazareno Buiatti', '6ta Caballeros', 'nazareno.buiatti@circuito.nortepadel', 250.0, false),
  ('Facundo Loprette', '6ta Caballeros', 'facundo.loprette@circuito.nortepadel', 0, true),
  ('Facundo Loprette', '5ta Caballeros', 'facundo.loprette2@circuito.nortepadel', 2500.0, false),
  ('Facundo Loprette', '4ta Caballeros', 'facundo.loprette3@circuito.nortepadel', 250.0, false),
  ('Marcos Rodriguez', '6ta Caballeros', 'marcos.rodriguez@circuito.nortepadel', 250.0, false),
  ('Robiño', '6ta Caballeros', 'robino@circuito.nortepadel', 250.0, false),
  ('Robiño', '5ta Caballeros', 'robino2@circuito.nortepadel', 100.0, false),
  ('Miqueas Arregin', '6ta Caballeros', 'miqueas.arregin@circuito.nortepadel', 250.0, false),
  ('Claudio Alvarez', '6ta Caballeros', 'claudio.alvarez@circuito.nortepadel', 225.0, false),
  ('Lucas Casales', '6ta Caballeros', 'lucas.casales@circuito.nortepadel', 200.0, false),
  ('Alejandro Marquez', '6ta Caballeros', 'alejandro.marquez@circuito.nortepadel', 125.0, false),
  ('Jordan Fagundez', '6ta Caballeros', 'jordan.fagundez@circuito.nortepadel', 125.0, false),
  ('Jeremias Arregin', '6ta Caballeros', 'jeremias.arregin@circuito.nortepadel', 125.0, false),
  ('Denis Ramirez', '6ta Caballeros', 'denis.ramirez@circuito.nortepadel', 125.0, false),
  ('Facundo Vera', '6ta Caballeros', 'facundo.vera@circuito.nortepadel', 125.0, false),
  ('Facundo Vera', '5ta Caballeros', 'facundo.vera2@circuito.nortepadel', 0, true),
  ('Facundo Vera', '4ta Caballeros', 'facundo.vera3@circuito.nortepadel', 2250.0, false),
  ('Iordan Abdalla', '6ta Caballeros', 'iordan.abdalla@circuito.nortepadel', 125.0, false),
  ('Francisco Paiva', '6ta Caballeros', 'francisco.paiva@circuito.nortepadel', 125.0, false),
  ('Gabriel Cardozo', '6ta Caballeros', 'gabriel.cardozo@circuito.nortepadel', 125.0, false),
  ('Nicolas Meza', '6ta Caballeros', 'nicolas.meza@circuito.nortepadel', 125.0, false),
  ('Sofia Galeano', '6ta Caballeros', 'sofia.galeano@circuito.nortepadel', 125.0, false),
  ('Lautaro Rivero', '6ta Caballeros', 'lautaro.rivero@circuito.nortepadel', 125.0, false),
  ('Ricardo Monges', '6ta Caballeros', 'ricardo.monges@circuito.nortepadel', 125.0, false),
  ('Lucas Zacarias', '6ta Caballeros', 'lucas.zacarias@circuito.nortepadel', 125.0, false),
  ('Rodri Cabañas', '6ta Caballeros', 'rodri.cabanas@circuito.nortepadel', 125.0, false),
  ('Eze Avalos', '6ta Caballeros', 'eze.avalos@circuito.nortepadel', 125.0, false),
  ('Gustavo Lorenzo', '6ta Caballeros', 'gustavo.lorenzo@circuito.nortepadel', 125.0, false),
  ('Gustavo Lorenzo', '5ta Caballeros', 'gustavo.lorenzo2@circuito.nortepadel', 125.0, false),
  ('Alan Jagner', '6ta Caballeros', 'alan.jagner@circuito.nortepadel', 125.0, false),
  ('Lucas Cardozo', '6ta Caballeros', 'lucas.cardozo@circuito.nortepadel', 125.0, false),
  ('Emiliano Rolon', '6ta Caballeros', 'emiliano.rolon@circuito.nortepadel', 125.0, false),
  ('Javier Pereira', '6ta Caballeros', 'javier.pereira@circuito.nortepadel', 125.0, false),
  ('Franco Kelm', '6ta Caballeros', 'franco.kelm@circuito.nortepadel', 125.0, false),
  ('Lucas Gautschi', '5ta Caballeros', 'lucas.gautschi@circuito.nortepadel', 3000.0, false),
  ('Ema Valenzuela', '5ta Caballeros', 'ema.valenzuela@circuito.nortepadel', 2500.0, false),
  ('Ema Valenzuela', '4ta Caballeros', 'ema.valenzuela2@circuito.nortepadel', 125.0, false),
  ('Josias Figueredo', '5ta Caballeros', 'josias.figueredo@circuito.nortepadel', 2250.0, false),
  ('Josias Figueredo', '4ta Caballeros', 'josias.figueredo2@circuito.nortepadel', 375.0, false),
  ('Leo Ferreira', '5ta Caballeros', 'leo.ferreira@circuito.nortepadel', 2125.0, false),
  ('Cutu Gonzalez', '5ta Caballeros', 'cutu.gonzalez@circuito.nortepadel', 1875.0, false),
  ('Ale Valenzuela', '5ta Caballeros', 'ale.valenzuela@circuito.nortepadel', 1750.0, false),
  ('Maxi Beltran', '5ta Caballeros', 'maxi.beltran@circuito.nortepadel', 1600.0, false),
  ('Juan Alegre', '5ta Caballeros', 'juan.alegre@circuito.nortepadel', 0, true),
  ('Juan Alegre', '4ta Caballeros', 'juan.alegre2@circuito.nortepadel', 1750.0, false),
  ('Juan Alegre', '3ra Caballeros', 'juan.alegre3@circuito.nortepadel', 375.0, false),
  ('Andres Gil', '5ta Caballeros', 'andres.gil@circuito.nortepadel', 1500.0, false),
  ('Andres Gil', '4ta Caballeros', 'andres.gil2@circuito.nortepadel', 125.0, false),
  ('Gonzalo Sosa', '5ta Caballeros', 'gonzalo.sosa@circuito.nortepadel', 1500.0, false),
  ('Maxi Benitez', '5ta Caballeros', 'maxi.benitez@circuito.nortepadel', 1375.0, false),
  ('Richard Gonzalez', '5ta Caballeros', 'richard.gonzalez@circuito.nortepadel', 1375.0, false),
  ('Juan Martinez', '4ta Caballeros', 'juan.martinez@circuito.nortepadel', 1000.0, false),
  ('Maxi Zamudio', '5ta Caballeros', 'maxi.zamudio@circuito.nortepadel', 1125.0, false),
  ('Maxi Reisdorfer', '4ta Caballeros', 'maxi.reisdorfer@circuito.nortepadel', 0, true),
  ('Armando Bareiro', '5ta Caballeros', 'armando.bareiro@circuito.nortepadel', 0, true),
  ('Armando Bareiro', '4ta Caballeros', 'armando.bareiro2@circuito.nortepadel', 1625.0, false),
  ('Armando Bareiro', '3ra Caballeros', 'armando.bareiro3@circuito.nortepadel', 625.0, false),
  ('Pitu Busch', '5ta Caballeros', 'pitu.busch@circuito.nortepadel', 1000.0, false),
  ('Lucas Schuaitzer', '5ta Caballeros', 'lucas.schuaitzer@circuito.nortepadel', 1000.0, false),
  ('Gaston Corbey', '5ta Caballeros', 'gaston.corbey@circuito.nortepadel', 875.0, false),
  ('Fernan Diaz', '5ta Caballeros', 'fernan.diaz@circuito.nortepadel', 875.0, false),
  ('Ignacio Gonzalez', '5ta Caballeros', 'ignacio.gonzalez@circuito.nortepadel', 875.0, false),
  ('Agustin Zavala', '5ta Caballeros', 'agustin.zavala@circuito.nortepadel', 875.0, false),
  ('Juan Pacheco', '5ta Caballeros', 'juan.pacheco@circuito.nortepadel', 750.0, false),
  ('Mauricio Miranda', '5ta Caballeros', 'mauricio.miranda@circuito.nortepadel', 750.0, false),
  ('Mauricio Miranda', '3ra Caballeros', 'mauricio.miranda2@circuito.nortepadel', 250.0, false),
  ('Rodrigo Vera', '5ta Caballeros', 'rodrigo.vera@circuito.nortepadel', 750.0, false),
  ('Eliezer Rodriguez', '5ta Caballeros', 'eliezer.rodriguez@circuito.nortepadel', 0, true),
  ('Eliezer Rodriguez', '4ta Caballeros', 'eliezer.rodriguez2@circuito.nortepadel', 1487.5, false),
  ('Eliezer Rodriguez', '3ra Caballeros', 'eliezer.rodriguez3@circuito.nortepadel', 250.0, false),
  ('Ariel Aquino', '5ta Caballeros', 'ariel.aquino@circuito.nortepadel', 700.0, false),
  ('Guillermo Lozina', '4ta Caballeros', 'guillermo.lozina@circuito.nortepadel', 1562.5, false),
  ('Matias Rivas', '5ta Caballeros', 'matias.rivas@circuito.nortepadel', 625.0, false),
  ('Leo Lopez', '5ta Caballeros', 'leo.lopez@circuito.nortepadel', 600.0, false),
  ('Joa Pereira', '5ta Caballeros', 'joa.pereira@circuito.nortepadel', 0, true),
  ('Joa Pereira', '3ra Caballeros', 'joa.pereira2@circuito.nortepadel', 250.0, false),
  ('Federico Pfefferkorn', '5ta Caballeros', 'federico.pfefferkorn@circuito.nortepadel', 500.0, false),
  ('Claudio Milarque', '5ta Caballeros', 'claudio.milarque@circuito.nortepadel', 500.0, false),
  ('Diego Garcia', '5ta Caballeros', 'diego.garcia@circuito.nortepadel', 475.0, false),
  ('Joa Dachary', '5ta Caballeros', 'joa.dachary@circuito.nortepadel', 475.0, false),
  ('Alex Lopez', '5ta Caballeros', 'alex.lopez@circuito.nortepadel', 475.0, false),
  ('Josue Raynoldi', '5ta Caballeros', 'josue.raynoldi@circuito.nortepadel', 350.0, false),
  ('Edu Ferreira', '5ta Caballeros', 'edu.ferreira@circuito.nortepadel', 350.0, false),
  ('Nahuel Blanco', '5ta Caballeros', 'nahuel.blanco@circuito.nortepadel', 350.0, false),
  ('Cesar Mamani', '5ta Caballeros', 'cesar.mamani@circuito.nortepadel', 325.0, false),
  ('Hector Villalba', '5ta Caballeros', 'hector.villalba@circuito.nortepadel', 250.0, false),
  ('Octavio Esteche', '5ta Caballeros', 'octavio.esteche@circuito.nortepadel', 250.0, false),
  ('Ale Spinola', '5ta Caballeros', 'ale.spinola@circuito.nortepadel', 250.0, false),
  ('Dani Ortiz', '5ta Caballeros', 'dani.ortiz@circuito.nortepadel', 0, true),
  ('Diego Molinelli', '5ta Caballeros', 'diego.molinelli@circuito.nortepadel', 250.0, false),
  ('Gutavo Zavala', '5ta Caballeros', 'gutavo.zavala@circuito.nortepadel', 250.0, false),
  ('Robson', '5ta Caballeros', 'robson@circuito.nortepadel', 250.0, false),
  ('Cristian Ruiz Cobo', '5ta Caballeros', 'cristian.ruiz.cobo@circuito.nortepadel', 250.0, false),
  ('Federico Montenegro', '5ta Caballeros', 'federico.montenegro@circuito.nortepadel', 250.0, false),
  ('Alejo Medina', '5ta Caballeros', 'alejo.medina@circuito.nortepadel', 250.0, false),
  ('Maximo Borja', '5ta Caballeros', 'maximo.borja@circuito.nortepadel', 225.0, false),
  ('Maximo Borja', '4ta Caballeros', 'maximo.borja2@circuito.nortepadel', 125.0, false),
  ('Nahuel Cerioli', '5ta Caballeros', 'nahuel.cerioli@circuito.nortepadel', 125.0, false),
  ('Ale Conrrado', '5ta Caballeros', 'ale.conrrado@circuito.nortepadel', 125.0, false),
  ('Maxi Morinigo', '5ta Caballeros', 'maxi.morinigo@circuito.nortepadel', 125.0, false),
  ('Agusto Gruber', '5ta Caballeros', 'agusto.gruber@circuito.nortepadel', 125.0, false),
  ('Elias Bogado', '5ta Caballeros', 'elias.bogado@circuito.nortepadel', 125.0, false),
  ('Elias Bogado', '4ta Caballeros', 'elias.bogado2@circuito.nortepadel', 750.0, false),
  ('Jose Benitez', '5ta Caballeros', 'jose.benitez@circuito.nortepadel', 125.0, false),
  ('Jose Benitez', '4ta Caballeros', 'jose.benitez2@circuito.nortepadel', 125.0, false),
  ('Pablo Bergonzini', '5ta Caballeros', 'pablo.bergonzini@circuito.nortepadel', 125.0, false),
  ('Cristian Tierling', '5ta Caballeros', 'cristian.tierling@circuito.nortepadel', 100.0, false),
  ('Luciano Weber', '5ta Caballeros', 'luciano.weber@circuito.nortepadel', 100.0, false),
  ('Francisco Correa', '5ta Caballeros', 'francisco.correa@circuito.nortepadel', 100.0, false),
  ('Elias Polachini', '5ta Caballeros', 'elias.polachini@circuito.nortepadel', 100.0, false),
  ('Andres Roja', '5ta Caballeros', 'andres.roja@circuito.nortepadel', 100.0, false),
  ('Matias Alzamura', '5ta Caballeros', 'matias.alzamura@circuito.nortepadel', 0.0, false),
  ('Lucas Klis', '4ta Caballeros', 'lucas.klis@circuito.nortepadel', 3250.0, false),
  ('Oscar Ocampo', '4ta Caballeros', 'oscar.ocampo@circuito.nortepadel', 3000.0, false),
  ('Santiago Ortiz', '3ra Caballeros', 'santiago.ortiz@circuito.nortepadel', 2250.0, false),
  ('Juan Scarano', '4ta Caballeros', 'juan.scarano@circuito.nortepadel', 2750.0, false),
  ('Gonzalo Alegre', '4ta Caballeros', 'gonzalo.alegre@circuito.nortepadel', 2625.0, false),
  ('Rene Alvez', '4ta Caballeros', 'rene.alvez@circuito.nortepadel', 2375.0, false),
  ('Rodri Ferreira', '4ta Caballeros', 'rodri.ferreira@circuito.nortepadel', 2125.0, false),
  ('Rodri Ferreira', '3ra Caballeros', 'rodri.ferreira2@circuito.nortepadel', 750.0, false),
  ('Joaquin Pereira', '4ta Caballeros', 'joaquin.pereira@circuito.nortepadel', 2125.0, false),
  ('Fabricio Zavala', '4ta Caballeros', 'fabricio.zavala@circuito.nortepadel', 2000.0, false),
  ('Fabricio Zavala', '3ra Caballeros', 'fabricio.zavala2@circuito.nortepadel', 250.0, false),
  ('Fredy Zamudio', '4ta Caballeros', 'fredy.zamudio@circuito.nortepadel', 1875.0, false),
  ('Martin Ferreira', '4ta Caballeros', 'martin.ferreira@circuito.nortepadel', 1750.0, false),
  ('Lucas Correa', '4ta Caballeros', 'lucas.correa@circuito.nortepadel', 1250.0, false),
  ('Lucas Correa', '3ra Caballeros', 'lucas.correa2@circuito.nortepadel', 250.0, false),
  ('Alexis Chagas', '4ta Caballeros', 'alexis.chagas@circuito.nortepadel', 1125.0, false),
  ('Alexis Chagas', '3ra Caballeros', 'alexis.chagas2@circuito.nortepadel', 375.0, false),
  ('Daniel Ortiz', '4ta Caballeros', 'daniel.ortiz@circuito.nortepadel', 1125.0, false),
  ('Diego Romero', '4ta Caballeros', 'diego.romero@circuito.nortepadel', 1125.0, false),
  ('Agustin Kunzeman', '3ra Caballeros', 'agustin.kunzeman@circuito.nortepadel', 500.0, false),
  ('Matias Andino', '4ta Caballeros', 'matias.andino@circuito.nortepadel', 875.0, false),
  ('Nicolas Rojas', '4ta Caballeros', 'nicolas.rojas@circuito.nortepadel', 625.0, false),
  ('Mariano Agustini', '4ta Caballeros', 'mariano.agustini@circuito.nortepadel', 625.0, false),
  ('Maxi Britez', '4ta Caballeros', 'maxi.britez@circuito.nortepadel', 500.0, false),
  ('Javier Saucedo', '4ta Caballeros', 'javier.saucedo@circuito.nortepadel', 500.0, false),
  ('Cristian Cobo', '4ta Caballeros', 'cristian.cobo@circuito.nortepadel', 500.0, false),
  ('Ale Villalba', '4ta Caballeros', 'ale.villalba@circuito.nortepadel', 500.0, false),
  ('Enzo Villalba', '4ta Caballeros', 'enzo.villalba@circuito.nortepadel', 500.0, false),
  ('Raul Kraus', '4ta Caballeros', 'raul.kraus@circuito.nortepadel', 500.0, false),
  ('Daniel Rotela', '4ta Caballeros', 'daniel.rotela@circuito.nortepadel', 500.0, false),
  ('Gonza Sosa', '4ta Caballeros', 'gonza.sosa@circuito.nortepadel', 500.0, false),
  ('Augusto Espinola', '4ta Caballeros', 'augusto.espinola@circuito.nortepadel', 500.0, false),
  ('Gabriel Gularte', '4ta Caballeros', 'gabriel.gularte@circuito.nortepadel', 500.0, false),
  ('Jose Flores', '4ta Caballeros', 'jose.flores@circuito.nortepadel', 500.0, false),
  ('Jose Flores', '3ra Caballeros', 'jose.flores2@circuito.nortepadel', 750.0, false),
  ('Chochin Britez', '4ta Caballeros', 'chochin.britez@circuito.nortepadel', 375.0, false),
  ('Maxi Krieguer', '4ta Caballeros', 'maxi.krieguer@circuito.nortepadel', 375.0, false),
  ('Leo Scaner', '4ta Caballeros', 'leo.scaner@circuito.nortepadel', 375.0, false),
  ('Enzo Buiatti', '4ta Caballeros', 'enzo.buiatti@circuito.nortepadel', 250.0, false),
  ('Guillermo Guidi', '4ta Caballeros', 'guillermo.guidi@circuito.nortepadel', 250.0, false),
  ('Diego Balbuena', '4ta Caballeros', 'diego.balbuena@circuito.nortepadel', 250.0, false),
  ('Pablo Allou', '4ta Caballeros', 'pablo.allou@circuito.nortepadel', 250.0, false),
  ('Marcos', '4ta Caballeros', 'marcos@circuito.nortepadel', 250.0, false),
  ('Agusitn Rojas', '4ta Caballeros', 'agusitn.rojas@circuito.nortepadel', 250.0, false),
  ('Sergio Recalde', '4ta Caballeros', 'sergio.recalde@circuito.nortepadel', 250.0, false),
  ('Chito Gonzalez', '4ta Caballeros', 'chito.gonzalez@circuito.nortepadel', 125.0, false),
  ('Franco Presti', '4ta Caballeros', 'franco.presti@circuito.nortepadel', 125.0, false),
  ('Sergio Rojas', '4ta Caballeros', 'sergio.rojas@circuito.nortepadel', 125.0, false),
  ('Julio Vargas', '4ta Caballeros', 'julio.vargas@circuito.nortepadel', 125.0, false),
  ('Julio Vargas', '3ra Caballeros', 'julio.vargas2@circuito.nortepadel', 625.0, false),
  ('Mateo Gusto', '4ta Caballeros', 'mateo.gusto@circuito.nortepadel', 125.0, false),
  ('Ale Espinola', '4ta Caballeros', 'ale.espinola@circuito.nortepadel', 125.0, false),
  ('Mauri Miranda', '4ta Caballeros', 'mauri.miranda@circuito.nortepadel', 125.0, false),
  ('Agustin Monges', '3ra Caballeros', 'agustin.monges@circuito.nortepadel', 4000.0, false),
  ('Rodrigo Schreiner', '3ra Caballeros', 'rodrigo.schreiner@circuito.nortepadel', 3250.0, false),
  ('Juanchi Caceres', '3ra Caballeros', 'juanchi.caceres@circuito.nortepadel', 3250.0, false),
  ('Lautaro Caballero', '3ra Caballeros', 'lautaro.caballero@circuito.nortepadel', 3250.0, false),
  ('Javier Gonzalez', '3ra Caballeros', 'javier.gonzalez@circuito.nortepadel', 2750.0, false),
  ('Martin Palacios', '3ra Caballeros', 'martin.palacios@circuito.nortepadel', 2500.0, false),
  ('Felipe Portillo', '3ra Caballeros', 'felipe.portillo@circuito.nortepadel', 2375.0, false),
  ('Damian Barbudez', '3ra Caballeros', 'damian.barbudez@circuito.nortepadel', 2375.0, false),
  ('Gian Garcia', '3ra Caballeros', 'gian.garcia@circuito.nortepadel', 2250.0, false),
  ('Nicolas Piriz', '3ra Caballeros', 'nicolas.piriz@circuito.nortepadel', 2125.0, false),
  ('Maxi Rodriguez', '3ra Caballeros', 'maxi.rodriguez@circuito.nortepadel', 2125.0, false),
  ('Angel Martinez', '3ra Caballeros', 'angel.martinez@circuito.nortepadel', 1875.0, false),
  ('Mateo Irrazabal', '3ra Caballeros', 'mateo.irrazabal@circuito.nortepadel', 1500.0, false),
  ('Maxi Caceres', '3ra Caballeros', 'maxi.caceres@circuito.nortepadel', 1250.0, false),
  ('Eduardo Bassi', '3ra Caballeros', 'eduardo.bassi@circuito.nortepadel', 1125.0, false),
  ('Mani Dornelles', '3ra Caballeros', 'mani.dornelles@circuito.nortepadel', 1000.0, false),
  ('Josias Agüero', '3ra Caballeros', 'josias.aguero@circuito.nortepadel', 750.0, false),
  ('Mandio Peralta', '3ra Caballeros', 'mandio.peralta@circuito.nortepadel', 500.0, false),
  ('Cristian Martinez', '3ra Caballeros', 'cristian.martinez@circuito.nortepadel', 375.0, false),
  ('Federico Maza', '3ra Caballeros', 'federico.maza@circuito.nortepadel', 375.0, false),
  ('Facu Vera', '3ra Caballeros', 'facu.vera@circuito.nortepadel', 375.0, false),
  ('Ignacio Spezini', '3ra Caballeros', 'ignacio.spezini@circuito.nortepadel', 250.0, false),
  ('Javier Balbuena', '3ra Caballeros', 'javier.balbuena@circuito.nortepadel', 250.0, false),
  ('Kichu Aquino', '3ra Caballeros', 'kichu.aquino@circuito.nortepadel', 250.0, false),
  ('Ivan Aguayo', '3ra Caballeros', 'ivan.aguayo@circuito.nortepadel', 125.0, false);

-- clave para agrupar por persona: normalmente el nombre completo. Pero si el
-- mismo nombre+categoría aparece más de una vez (ej "Patricio Esquivel" dos
-- veces en "6ta Caballeros"), son DOS personas reales distintas con el mismo
-- nombre, no la misma jugando dos categorías — a esas no las agrupamos,
-- quedan como cuentas separadas (cada una ya tiene su propio usuario).
update _recuperacion_circuito set clave_persona = nombre_completo;
update _recuperacion_circuito t
set clave_persona = t.usuario
where exists (
  select 1 from _recuperacion_circuito t2
  where t2.nombre_completo = t.nombre_completo
    and t2.categoria = t.categoria
    and t2.usuario <> t.usuario
);

select count(*) as filas_cargadas from _recuperacion_circuito;
select count(*) as necesitan_revision from _recuperacion_circuito where necesita_revision;
select nombre_completo, categoria, usuario from _recuperacion_circuito
where clave_persona = usuario order by nombre_completo;
